<?php

/**
 * BaseGitHubRepo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $repo_name
 * @property Doctrine_Collection $GitRepo
 * @property GitHubIssue $GitHubRepo
 * 
 * @method integer             getUserId()     Returns the current record's "user_id" value
 * @method string              getRepoName()   Returns the current record's "repo_name" value
 * @method Doctrine_Collection getGitRepo()    Returns the current record's "GitRepo" collection
 * @method GitHubIssue         getGitHubRepo() Returns the current record's "GitHubRepo" value
 * @method GitHubRepo          setUserId()     Sets the current record's "user_id" value
 * @method GitHubRepo          setRepoName()   Sets the current record's "repo_name" value
 * @method GitHubRepo          setGitRepo()    Sets the current record's "GitRepo" collection
 * @method GitHubRepo          setGitHubRepo() Sets the current record's "GitHubRepo" value
 * 
 * @package    charitycoding
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGitHubRepo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_repo');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('repo_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));

        $this->option('type', 'InnoDB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('sfGuardUser as GitRepo', array(
             'local' => 'id',
             'foreign' => 'id'));

        $this->hasOne('GitHubIssue as GitHubRepo', array(
             'local' => 'id',
             'foreign' => 'repo_id'));
    }
}