<?php

/**
 * BaseUserDetails
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $github_username
 * @property sfGuardUser $User
 * 
 * @method string      getGithubUsername()  Returns the current record's "github_username" value
 * @method sfGuardUser getUser()            Returns the current record's "User" value
 * @method UserDetails setGithubUsername()  Sets the current record's "github_username" value
 * @method UserDetails setUser()            Sets the current record's "User" value
 * 
 * @package    charitycoding
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserDetails extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_detail');
        $this->hasColumn('github_username', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));

        $this->option('type', 'InnoDB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'id',
             'foreign' => 'id'));
    }
}