<?php

/**
 * BaseGitHubAccount
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $github_repo
 * @property Doctrine_Collection $GitRepo
 * 
 * @method string              getGithubRepo()  Returns the current record's "github_repo" value
 * @method Doctrine_Collection getGitRepo()     Returns the current record's "GitRepo" collection
 * @method GitHubAccount       setGithubRepo()  Sets the current record's "github_repo" value
 * @method GitHubAccount       setGitRepo()     Sets the current record's "GitRepo" collection
 * 
 * @package    charitycoding
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGitHubAccount extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_repo');
        $this->hasColumn('github_repo', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));

        $this->option('type', 'InnoDB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('sfGuardUser as GitRepo', array(
             'local' => 'id',
             'foreign' => 'id'));
    }
}