<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/11/03 15:16:46

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=charitycoding',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
