<?php

/**
 * GitHubRepoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GitHubRepoTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object GitHubRepoTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('GitHubRepo');
    }

    /**
     * fetch all the user repos
     * @param type $userId
     * @return type 
     */
    public static function getUserRepos($userId)
    {
	// create the query
	$q = Doctrine_Query::create();
	$q->select("g.repo_name");
	$q->from("GitHubRepo g");        
	$q->addWhere("g.user_id = ?", $userId);        
	// execute the query and return the resultset
        return $q->fetchArray();                
    }
    
    /**
     * check if a github username is already registered
     * @param type $githubUsername
     * @return boolean 
     */
    public static function checkRepoNameExists($repoName)
    {
	// create the query
	$q = Doctrine_Query::create();
	$q->select("g.repo_name");
	$q->from("GitHubRepo g");        
	$q->addWhere("g.repo_name = ?", $repoName);        
	// execute the query and return the resultset
        $res = $q->fetchArray();
        if(count($res) > 0) {
            // name exists
            return true;
        } else {
            // name doesnt exist
            return false;
        }
    }         
}