<?php

/**
 * GitHubIssueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GitHubIssueTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GitHubIssueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GitHubIssue');
    }
}