# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing
registration:
  url:   /registration
  param: { module: registration, action: index }

list_user_repo:
  url:   /user_repos
  param: { module: registration, action: listUserRepo }

list_user_issues:
  url:   /list_issues
  param: { module: registration, action: listIssues }

create_just_giving_page:
  url:   /create_just_giving_page
  param: { module: registration, action: createJustGivingPage }

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }
  
# default rules
homepage:
  url:   /
  param: { module: home, action: index }