<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/11/03 15:13:03
sfConfig::add(array(
  'sf_error_404_module' => 'default',
  'sf_error_404_action' => 'error404',
  'sf_login_module' => 'default',
  'sf_login_action' => 'login',
  'sf_secure_module' => 'default',
  'sf_secure_action' => 'secure',
  'sf_module_disabled_module' => 'default',
  'sf_module_disabled_action' => 'disabled',
  'sf_use_database' => true,
  'sf_i18n' => false,
  'sf_compressed' => false,
  'sf_check_lock' => false,
  'sf_csrf_secret' => false,
  'sf_escaping_strategy' => false,
  'sf_escaping_method' => 'ESC_SPECIALCHARS',
  'sf_no_script_name' => false,
  'sf_cache' => false,
  'sf_etag' => false,
  'sf_web_debug' => false,
  'sf_error_reporting' => 32759,
  'sf_file_link_format' => NULL,
  'sf_admin_web_dir' => '/sf/sf_admin',
  'sf_web_debug_web_dir' => '/sf/sf_web_debug',
  'sf_standard_helpers' => array (
  0 => 'Partial',
  1 => 'Cache',
),
  'sf_enabled_modules' => array (
  0 => 'default',
),
  'sf_charset' => 'utf-8',
  'sf_logging_enabled' => true,
  'sf_default_culture' => 'en',
  'sf_all_.settings' => array (
  'enabled_modules' => 
  array (
    0 => 'default',
    1 => 'sfGuardAuth',
  ),
),
  'sf_all_login_module' => 'sfGuardAuth',
  'sf_all_login_action' => 'signin',
  'sf_all_secure_module' => 'sfGuardAuth',
  'sf_all_secure_action' => 'secure',
  'sf_all_csrf_secret' => '401ca2f2a730a3da6990a16316267ac4bd859f57',
  'sf_all_escaping_strategy' => true,
  'sf_all_escaping_method' => 'ESC_SPECIALCHARS',
  'sf_all_use_database' => true,
));
