<?php
// auto-generated by sfSecurityConfigHandler
// date: 2012/11/03 21:40:05
$this->security = array (
  'createjustgivingpage' => 
  array (
    'is_secure' => true,
  ),
  'listuserissues' => 
  array (
    'is_secure' => true,
  ),
  'listuserrepo' => 
  array (
    'is_secure' => true,
  ),
  'secure' => 
  array (
    'is_secure' => false,
  ),
  'signin' => 
  array (
    'is_secure' => false,
  ),
  'signout' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
  ),
);
