<?php
// auto-generated by sfSecurityConfigHandler
// date: 2012/11/03 21:37:17
$this->security = array (
  'listuserissues' => 
  array (
    'is_secure' => true,
  ),
  'listuserrepo' => 
  array (
    'is_secure' => true,
  ),
  'all' => 
  array (
  ),
);
