UserDetails:
  options:
    type: InnoDB
    collate: utf8_unicode_ci
    charset: utf8    
  tableName: user_detail
  columns:
    user_id: { type: integer } 
    github_username: { type: string(255), notnull: true } 
  relations:
    User: { class: sfGuardUser, local: id, foreignAlias: sfGuardUser, type: one }    
    
GitHubRepo:
  options:
    type: InnoDB
    collate: utf8_unicode_ci
    charset: utf8    
  tableName: user_repo
  columns:
    user_id: { type: integer } 
    repo_name: { type: string(255), notnull: true } 
  relations:
    GitRepo: { class: sfGuardUser, local: id, foreignAlias: sfGuardUser, type: many }    
    
GitHubIssue:
  options:
    type: InnoDB
    collate: utf8_unicode_ci
    charset: utf8    
  tableName: user_issue
  columns:
    repo_id: { type: integer } 
    user_id: { type: integer } 
    issue_number: { type: integer } 
    donation_amount: { type: integer }
  relations:
    GitIssue: { class: GitHubRepo, local: repo_id, foreign: id, foreignAlias: GitHubRepo, type: many }        